version: '3'
services:
    web:
      build: .
      ports: 
          - 8080:8080
      depends_on:
          - db
    db:
        container_name: sample_db
        image: postgres:11.1
        volumes:
            - ./database:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=urlshortener
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        restart: unless-stopped
